<script>
  import Header from "../../components/Header.svelte";
  import FunGamesCard from "../../components/cards/FunGamesCard.svelte";
  import hrefs from "../../data/hrefs.json";
  import gamingImg from "../../images/svg/gaming.svg";
  const funGames = hrefs["fun-games"];
</script>

<Header directory="fun-games" activePage="home" title="Fun Games" />
<main class="text-bg-dark dark-background">
  <section>
    <div class="container">
      <div class="py-4">
        <h1>Welcome to <span class="text-warning">Fun Games</span></h1>
        <p class="font-google-quicksand fs-5 fw-500" />
      </div>
    </div>
    <div class="container">
      <div class="row py-4">
        <FunGamesCard
          gameLink={funGames["numberguess"]}
          title="Number Guesser"
          description="Put your guessing skills to the test as you take on the challenge of
        correctly predicting a random number generated by the computer. Take a
        shot at hitting the bullseye and find out if your guess is too high or
        too low."
          icon="arrow-up-1-9"
        />
        <FunGamesCard
          gameLink={funGames["wordguess"]}
          title="Word Guesser"
          description="This is a simple hangman game implemented in your web browser. The game randomly selects a word from a provided list of words and gives you a limited number of tries to guess the word correctly."
          icon="arrow-up-z-a"
        />
      </div>
    </div>
  </section>
</main>
