<script>
  import Header from "../../components/Header.svelte";
  import FunGamesCard from "../../components/cards/FunGamesCard.svelte";
  import hrefs from "../../data/hrefs.json";
  const directory = hrefs["fun-games"];
</script>

<main class="text-bg-dark full-background">
  <Header {directory} title={directory["home"]["title"]} />
  <section>
    <div class="container">
      <div class="py-4">
        <h1>Welcome to <span class="text-warning">Fun Games</span></h1>
        <div class="border-start ps-3 w-xxl-75">
          <p class="font-google-quicksand fs-5 fw-500">
            Fun Games offers enjoyable browser-based experiences. With
            user-friendly interfaces and straightforward gameplay, these
            accessible games entertain players of all skill levels. Explore and
            experience the joy of engaging browser-based entertainment.
          </p>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row py-4">
        <FunGamesCard
          gameLink={directory["numberguess"]["link"]}
          title={directory["numberguess"]["title"]}
          description="Put your guessing skills to the test as you take on the challenge of
        correctly predicting a random number generated by the computer. Take a
        shot at hitting the bullseye and find out if your guess is too high or
        too low."
          icon="arrow-up-1-9"
        />
        <FunGamesCard
          gameLink={directory["wordguess"]["link"]}
          title={directory["wordguess"]["title"]}
          description="This is a simple hangman game implemented in your web browser. The game randomly selects a word from a provided list of words and gives you a limited number of tries to guess the word correctly."
          icon="arrow-up-z-a"
        />
        <FunGamesCard
          gameLink={directory["reversenumberguess"]["link"]}
          title={directory["reversenumberguess"]["title"]}
          description={directory["reversenumberguess"]["description"]}
          icon="arrow-up-9-1"
        />
      </div>
    </div>
  </section>
</main>
